"""Async IMAP MailManager — alias dispatch + verification interception.

Connects to the catch-all mailbox `assistant@clubprivileges.app` and listens
for OTPs / activation links sent to per-deal sub-address aliases generated by
`generate_alias`.
"""
from __future__ import annotations

import asyncio
import email
import imaplib
import logging
import os
import re
from email.message import Message
from typing import Optional

from dotenv import load_dotenv

load_dotenv()
log = logging.getLogger(__name__)


OTP_RE = re.compile(r"(?<!\d)(\d{6})(?!\d)")
LINK_RE = re.compile(r"https?://[^\s\"'<>)]+", re.IGNORECASE)
EXCLUDE_LINK_HINTS = (
    "unsubscribe", "preferences", "manage-subscription", "manage_subscription",
    "list-manage", "tracking", "click.linksynergy", "mailto:",
    "/privacy", "/terms", "/cookie",
)


def _decode(payload: str | bytes | None) -> str:
    if payload is None:
        return ""
    if isinstance(payload, bytes):
        for enc in ("utf-8", "latin-1"):
            try:
                return payload.decode(enc, errors="replace")
            except Exception:
                continue
        return ""
    return payload


def _msg_text(msg: Message) -> str:
    parts: list[str] = []
    if msg.is_multipart():
        for part in msg.walk():
            if part.get_content_type() in ("text/plain", "text/html"):
                parts.append(_decode(part.get_payload(decode=True)))
    else:
        parts.append(_decode(msg.get_payload(decode=True)))
    return "\n".join(p for p in parts if p)


def _extract_otp(text: str) -> str | None:
    for match in OTP_RE.findall(text):
        return match
    return None


def _extract_activation_link(text: str) -> str | None:
    for url in LINK_RE.findall(text):
        if not any(hint in url.lower() for hint in EXCLUDE_LINK_HINTS):
            return url
    return None


class MailManager:
    """IMAP catch-all listener with per-alias verification interception."""

    def __init__(self) -> None:
        self.host = os.environ["IMAP_SERVER"]
        self.user = os.environ["IMAP_USER"]
        self.password = os.environ["IMAP_PASSWORD"]
        self.local_part, _, self.domain = self.user.partition("@")

    def generate_alias(self, partner_name: str) -> str:
        clean = re.sub(r"[^a-z0-9]+", "", (partner_name or "").lower())[:40] or "deal"
        return f"{self.local_part}+{clean}@{self.domain}"

    async def wait_for_verification(
        self,
        target_alias: str,
        timeout: int = 90,
    ) -> Optional[str]:
        """Poll IMAP every 5s until OTP or activation link, else None."""
        loop = asyncio.get_event_loop()
        deadline = loop.time() + timeout
        while loop.time() < deadline:
            value = await asyncio.to_thread(self._scan_once, target_alias)
            if value:
                log.info("Verification captured for %s", target_alias)
                return value
            await asyncio.sleep(5)
        log.warning("No verification mail for %s within %ds", target_alias, timeout)
        return None

    def _scan_once(self, target_alias: str) -> str | None:
        try:
            with imaplib.IMAP4_SSL(self.host) as mbox:
                mbox.login(self.user, self.password)
                mbox.select("INBOX")
                typ, data = mbox.search(None, "UNSEEN", "TO", f'"{target_alias}"')
                if typ != "OK" or not data or not data[0]:
                    return None
                for msg_id in data[0].split():
                    typ, payload = mbox.fetch(msg_id, "(RFC822)")
                    if typ != "OK" or not payload or not payload[0]:
                        continue
                    msg = email.message_from_bytes(payload[0][1])
                    body = _msg_text(msg)
                    value = _extract_otp(body) or _extract_activation_link(body)
                    if value:
                        mbox.store(msg_id, "+FLAGS", "\\Seen")
                        return value
        except Exception as exc:
            log.warning("IMAP scan failed: %s", exc)
        return None
